global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - gateway
        type: A
        port: 8001
    # Fallback for single-instance deployments
    static_configs:
      - targets: ["gateway:8001"]
